name: Autowini Pro Scraper

on:
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: 1. კოდის ჩამოტვირთვა
        uses: actions/checkout@v3

      - name: 2. ნოუდის დაყენება
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 3. სისტემური ბიბლიოთეკების დაყენება
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev wget gnupg libnss3 libatk-bridge2.0-0 libgtk-3-0 libasound2 xvfb

      - name: 4. პაკეტების დაყენება
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios

      - name: 5. სკრიპტის გაშვება XVFB-ით (გარანტირებული მუშაობა)
        # xvfb-run არის ის, რაც სერვერზე "X Server"-ს აიმიტირებს
        run: xvfb-run node scraper.js
